import type { Metadata } from "next";
import { Roboto } from "next/font/google"
import 'bootstrap/dist/css/bootstrap.css'
import { Container } from "react-bootstrap";
import "./global.scss"
const roboto = Roboto({ subsets: ["vietnamese"], weight: ["100", "300"] })

export const metadata: Metadata = {
  title: "Next_tutorial",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <Container>
          {children}
        </Container>
      </body>
    </html>
  );
}
